---
title: "Baltimore Murals"
author: "Leanne Fortney"
date: "April 10, 2017"
output:
  html_document: default
  pdf_document: default
---

```{r, echo=FALSE, include=FALSE}
library(sf)                  
library(leaflet)            
library(scales)             
library(cleanNLP)
library(ggmap)
```
```{r Data Input, echo=FALSE}
Baltimore_City_Murals <- read_csv("~/Desktop/School/Clio2/Baltimore City/Baltimore_Murals/Baltimore_Murals/Baltimore_City_Murals.csv",
     col_types =  cols( 
    location = col_character(),
    city = col_character(),
    state = col_character(),
    artistFirstName = col_character(),
    artistLastName = col_character(),
    YEAR = col_integer(),
    address = col_character()
))
```
```
In 1975, Baltimore City, Maryland, created the Baltimore Mural Program in hope to take back the community through city beautification program. During this time, Baltimore City also initiated a record keeping of murals with the city limits. This visualization, below, notes the locations of each mural that has been produced and recorded since the start of the program. The visualization includes the artist's name, the year it was produced, and the site location. When you zoom into an area, the targeted indicators remain true to the GPS coordinations, and though it reduced in size, it is only to meet the need to be more concise.

```

```{r Baltimore Sites, message=FALSE, warning=FALSE, include=FALSE}
artists <- Baltimore_City_Murals %>% 
    select(-address) %>% 
    mutate(artist_name = paste(artistFirstName, artistLastName, sep = " ")) 

site <- mutate(Baltimore_City_Murals, site = paste(location, city, state, sep = ", "))

select(artists, artist_name, location)
left_join(site, artists, copy= F)

coords <- geocode(site$site, output = "latlona")
address_coords <- bind_cols(artists, coords) 

Baltimore_City_Murals %>% 
  left_join(address_coords, by = c("location", "city", "state")) %>% 
 filter(!is.na(lat) & !is.na(lon))
```
```{r, echo=FALSE, message=FALSE, warning=FALSE}

leaflet(Baltimore_City_Murals) %>% 
  addTiles() %>% 
  addCircleMarkers(data = address_coords,
                   lng = ~lon, lat = ~lat, 
                   color = "#0004fc", weight = 1,
                   radius = 5,
                   popup = ~paste(artist_name, ", ", YEAR, '<br>', location))
```
```
It is amazing to see where the city first choose to have the murals. With the first mural completed in 1987 until 1990, you can see the tarrgeted areas that the city choose in order to fight gangs, girfitti, and to bring a sense of ownership to the community. These are, as seen below, were the areas that Baltimore felt would improve a greater sense of identity and pride of their community.  

```
```{r 13, include=FALSE}

Early <- address_coords %>% 
  filter(YEAR <= 1990)

Early %>% 
select(YEAR, location, lon, lat, artist_name)
```
```{r, echo=FALSE}
leaflet(Early) %>% 
  addTiles() %>% 
  addCircleMarkers(data = Early,
                   lng = ~lon, lat = ~lat, 
                   color = "#f90031", weight = 3,
                   radius = 5,
                   popup = ~paste(artist_name,",",YEAR, '<br>', location))

```


